theme: minima
title: z3ncowie's Blog
author: bretcowie
email: bcowie@zendesk.com
description: > # this means to ignore newlines until "baseurl:"
  This is my starter blog to help with Github learning.

# social links
github_username:  bretcowie

show_excerpts: true # set to false to remove excerpts on the homepage
